### ISSUE TITLE
Add CLI for Microsoft 365 to Reset files permissions unique to Inherited

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#114]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/reset-files-permission-unique-to-inherited/README.html?tabs=pnpps

**Comment by ValerasNarbutas** [comment]
@hugoabernier , Good afternoon, 
i will take this one.

**Comment by ValerasNarbutas** [comment]
@pkbullock / @Adam-it  looks like this one also not yet possible with CLI, 
CLI can only get file sharing info. 
Maybe it is worth to have the separate script "get all files in SharePoint library sharing information"

**Comment by Adam-it** [comment]
I think it is always a good idea to have a new sample 👍.
@ValerasNarbutas did you maybe check if there is some SP REST or graph API endpoint that support this functionality? 
Maybe we could add this as a lacking functionality to the m365 cli and add it 🤔

**Comment by ValerasNarbutas** [comment]
> 

@Adam-it  yeah, i will check for others, for CLI already asked in CLI questions, in repo, 
I saw some discussions were already been about inheritance on list items, at least list items with broken inheritance
we will see how it goes :)

**Comment by ValerasNarbutas** [comment]
Got confirmation from @waldekmastykarz option not yet available, it might be in the future. Maybe  i will contribute myself to cli to have this method. Tried Graph also, but code became too complicated to use in scriptsample.
I would say this issue can be closed for now. 
@pkbullock , @Adam-it

**Comment by Adam-it** [comment]
@ValerasNarbutas sure I agree 👍. Thanks for checking this out. Also I strongly encourage you to open an issue in [CLI](https://github.com/pnp/cli-microsoft365) to add this functionality 👍. If you would like to try but don't know how to start you may always reach out to me and I will try to help you and answer any of your questions (please be aware I am not an m365 CLI pro but I will do my best 😋). Also any opinion on how to improve the process for a new contributor to the CLI you may post here https://github.com/pnp/cli-microsoft365/issues/2834 as the m365 CLI team are trying  to improve this process 👍👍.
Also if just want to open an issue and you don't want to develop it or you don't have time for it that is totally fine and just tag me in it so maybe I could try.

**Comment by Adam-it** [comment]
ok since I can do it I am closing this issue for now as CLI does not support this functionality 👍 @ValerasNarbutas  thanks again for researching this 👍. You are awesome 👍

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas sure I agree 👍. Thanks for checking this out. Also I strongly encourage you to open an issue in [CLI](https://github.com/pnp/cli-microsoft365) to add this functionality 👍. If you would like to try but don't know how to start you may always reach out to me and I will try to help you and answer any of your questions (please be aware I am not an m365 CLI pro but I will do my best 😋). Also any opinion on how to improve the process for a new contributor to the CLI you may post here [pnp/cli-microsoft365#2834](https://github.com/pnp/cli-microsoft365/issues/2834) as the m365 CLI team are trying to improve this process 👍👍. Also if just want to open an issue and you don't want to develop it or you don't have time for it that is totally fine and just tag me in it so maybe I could try.

Thanks @Adam-it, i will open an issue anyway. i know how to start no worries, not my first rodeo :) and for sure you can try also. No questions from my side. thanks for closing.

**Comment by pkbullock** [comment]
Thank you both very much for your time and effort here @ValerasNarbutas @Adam-it really cool to see you pushing the boundaries of the underlying tools where possible.
