### ISSUE TITLE
Add CLI for Microsoft 365 to Read SharePoint List Items Using CAML Query

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#115]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-list-items-with-caml-query/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
ok this is the next one. @pkbullock could you please assign me to this issue 👍

**Comment by pkbullock** [comment]
Closing - sample complete :-)
