### ISSUE TITLE
Add CLI for Microsoft 365 to Export CSV To SharePoint List Data

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#116]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-export-data-to-sharepoint-lists/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
@pkbullock lets go with the next one 👍👍👍 ... ready, steady 🏃🏁 ... a wait I need to be assigned first 😉

**Comment by pkbullock** [comment]
This one is complete - happy days :-)
