### ISSUE TITLE
Add CLI for Microsoft 365 to Add a document library web part to a page (and only show a specific folder)

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#117]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-add-document-library-webpart-to-page/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
@pkbullock I would like to get assigned to this one. Could I get assigned? 
BTW did you checkout GitHub Action https://github.com/marketplace/actions/contributor-takes-action
it allows for contributors to assign themselves to an issue when they write some comment to an issue (like "take action") 🤔

**Comment by pkbullock** [comment]
Complete 😊

**Comment by pkbullock** [comment]
PS thanks for the above link - i thought since you created the issues that you can claim them. I will have a look at the GH action.
