### ISSUE TITLE
🧑‍💻Add CLI for Microsoft 365 to Generate Markdown Report of LCIDs

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#118]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/generate-markdown-lcids/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
@pkbullock  please assign me to this one

**Comment by Adam-it** [comment]
ok currently it is not supported to do it using m365 CLI.
@pkbullock like last time when I encountered similar problem I opened an issue in CLI repo and maybe I will be working on it as well. But if this will be developed we will need to wait some time for it to be shipped so the question is do we want to close this issue for now and reopen it when this feature will be ready? or we just leave it open for now?

**Comment by Adam-it** [comment]
ok we will be adding this functionality in this issue to CLI to support it https://github.com/pnp/cli-microsoft365/issues/2833
when this will be added I will add this example. For now lets leave this open 👍

**Comment by Adam-it** [comment]
ok the new functionality was developed and contributed to CLI I am waiting for new release of CLI which will have this command and then I may prepare a CLI version for this script as well 👍

**Comment by pkbullock** [comment]
Closing as you've kindly submitted the same and extended the CLI 👏
