### ISSUE TITLE
🧑‍💻Add CLI for Microsoft 365 to Get SharePoint Site Recycle Bin Items And Export It To CSV

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#119]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-recyclebin-items-to-csv/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
ok since I need to wait with the previous item I was thinking I could start working on this one in coming weekend 🤔.
@pkbullock  could I get assigned?

**Comment by Adam-it** [comment]
Ok I checked this one and it turned out m365 CLI also does not support recycle bin 🤔. So I will create an issue in CLI and try to add this functionality, after that I will get back to this sample. @pkbullock so for now this will be as well on hold 👍 and will start working on adding this functionality

**Comment by Adam-it** [comment]
ok new command added to CLI (`m365 spo site recyclebinitem list`) in order to add the CLI version for this script and added a CLI version for this sample script (PR opened) 👍
This new command in CLI is a good motivation to look dipper in this functionality as it turned out that CLI for M365 till now did not support recycle bin functionality at all 🤩.
Also this PR will close the last issue added with the list of issues of adding 14 CLI versions for script samples 🤩🤩. 14 CLI versions and 14 weeks of open source work 🙂 I feel like I am going to celebrate this a bit😜

**Comment by pkbullock** [comment]
Closing this as implemented.
