### ISSUE TITLE
Sample for bulk deploying list formatting

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#12]
Based on this article: https://capacreative.co.uk/2018/02/11/using-pnp-powershell-to-apply-modern-column-formatting/

**Comment by ValerasNarbutas** [comment]
Hey, @pkbullock , i can do this one also, I have checked your blog post and will reuse it plus maybe add an additional action to copy format from the existing list to apply on another site.

**Comment by pkbullock** [comment]
Absolutely go for it :-)

**Comment by pkbullock** [comment]
Closing as completed - thank you!
