### ISSUE TITLE
Add CLI for Microsoft 365 to Report of Private Teams channels to Excel

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#120]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/report-private-teams-excel/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
@pkbullock the last one also needs to wait for this functionality to be added to m365 CLI. Could I get assigned to this one ?

**Comment by pkbullock** [comment]
Complete 😊
