### ISSUE TITLE
🧑‍💻Add CLI for Microsoft 365 to Remove delete option on a document library

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#121]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/remove-delete-option-library/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
@pkbullock could I get assigned to this one?
it seems this is the last one from the list I added that is either not done nor started 😎.

**Comment by pkbullock** [comment]
Hi Adam, i' ve installed that plugin you suggested so future claims, use a comment ".take" to claim the issue. See how it goes.

**Comment by Adam-it** [comment]
@pkbullock  That is so cool 👍
BTW .take

**Comment by ValerasNarbutas** [comment]
> Hi Adam, i' ve installed that plugin you suggested so future claims, use a comment ".take" to claim the issue. See how it goes.

nice man!

**Comment by ValerasNarbutas** [comment]
ups.. lookslike bot took "take" from quote :))) @Adam-it  take it back :)

**Comment by Adam-it** [comment]
@ValerasNarbutas  I think it is always possible  to unassign yourself at the top ( I guess I don't have enough permission to do it 🤔)
![image](https://user-images.githubusercontent.com/58668583/143308519-c16a9444-a581-4356-af65-715b24853ff8.png)

**Comment by pkbullock** [comment]
Lol, the boy is being trialed. I might change the trigger word but involves making my own. Which might be cool. 

Have unassigned you @ValerasNarbutas

**Comment by pkbullock** [comment]
Closing as complete 😃
