### ISSUE TITLE
Bulk Create Teams for Test Environments

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#16]
Script for in bulk creating a set of teams for test environments

**Comment by dips365** [comment]
I would like to create script on it. Could you please assign to me ?

**Comment by pkbullock** [comment]
Hi Dipen

Please don’t work on this one, I recently submitted a sample yesterday and haven’t yet updated the issue.

Thank you

Paul

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pkbullock** [comment]
Closing as this one is already done.
