### ISSUE TITLE
Generate a report listing where a specific Term is used

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#160]
Prior to maintenance in the Term store it is usually a very good idea to know where a given Term is used.
The script (Powershell) will iterate the site collections , webs and lists, and output a csv file.

**Comment by pkbullock** [comment]
Hi @kasperbolarsen is this a task that you are working on or a sample idea?

**Comment by kasperbolarsen** [comment]
Hi Paul,

Both I guess :-) I have the script ready and just needs to understand how
to upload it.

Best regards

Kasper

man. 6. dec. 2021 18.05 skrev Paul Bullock ***@***.***>:

**Comment by ValerasNarbutas** [comment]
hey @kasperbolarsen , i can help you if you want, its is very straightforward

**Comment by pkbullock** [comment]
Link to PR #165

**Comment by pkbullock** [comment]
@kasperbolarsen you happy for me to close now this is live?

**Comment by kasperbolarsen** [comment]
Hi Paul

By all means, cheers

man. 20. dec. 2021 21.26 skrev Paul Bullock ***@***.***>:
