### ISSUE TITLE
List guests within Teams in a tenant

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#168]
Building on the report https://pnp.github.io/script-samples/spo-list-site-externalusers/README.html?tabs=cli-m365-ps 
that external users can be identified in SharePoint.

Guests may exist on Teams that have not yet accessed SharePoint. Need to validate if that scenario occurs where they may not be listed in the user list until they access SharePoint.

**Comment by Jitenparmar** [comment]
Hello @pkbullock, Can you please assign this script to me? I would like to contribute to this task.

**Comment by pkbullock** [comment]
Sure - thank you 😊

**Comment by Jitenparmar** [comment]
Hello @pkbullock, I am contributing for the first time. Can I write a script using Connect-MicrosoftTeams?

**Comment by pkbullock** [comment]
Sure, technically there are no limits to the tools used, I can always adapt the site to support. If you submit a contribution, i typically make small tweaks anyway to set these up.

**Comment by Jitenparmar** [comment]
Thank you so much.

**Comment by pkbullock** [comment]
This is done in #173
