### ISSUE TITLE
Sample Idea: Inventory Guest User SignIn activity to SharePoint List

### ISSUE THREAD

**Issue by pkskelly** [pnp/script-samples#171]
Just blogged about inventory of guest user sign-in activity at https://peteskelly.com/cli-graph-signin-actvity/.  Since this requires a P1 feature, was not sure if this would make the best sample.  Happy to add to this repository if it would add value.

**Comment by pkbullock** [comment]
This would make a great sample! We can put a note (happy to add that for you) for the dependency.

**Comment by pkskelly** [comment]
I'll set some time aside to create a PR.  Need to read the docs on contributing again :-). Been a while.
