### ISSUE TITLE
Add SharePoint Large list data to PnP Teamplate

### ISSUE THREAD

**Issue by Jitenparmar** [pnp/script-samples#174]
New Idea - When you create a PnP template list data is not exporting. To resolve this we can create a PnP PowerShell script that will add large list data to PnPTemplate.

**Comment by Jitenparmar** [comment]
@pkbullock Can you please assign this to me? I would like to work on this.

**Comment by kasperbolarsen** [comment]
Something like integrating the Add-PnPDataRowsToSiteTemplate function into the Get-PnPSiteTemplate?

**Comment by Jitenparmar** [comment]
@kasperbolarsen yes this function can help but with the large list, it throws threshold limit error so in that case, I need to write the query in such a way that it should not throw that error.

**Comment by pkbullock** [comment]
This is complete, closing :-)
