### ISSUE TITLE
Extend the existing create-dummy-docs-in-library to handle versioning

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#175]
Extend the existing create-dummy-docs-in-library sample to handle creation of a number of major and minor versions per document.

I have the code ready for a PR in a few days 

Should it be handled as a new sample or as a change to the existing sample?

**Comment by pkbullock** [comment]
Lets create a new sample please. Thank you.

**Comment by pkbullock** [comment]
This is complete in PR #184
