### ISSUE TITLE
Sample on how to iterate Site Collections in parallel using foreach-object

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#189]
Hi

I have been looking into reducing the execution time when updating a lot of site collections by using Foreach-Object -parallel.

I am not sure if that kind of sample fits the purpose of this repository ?

**Comment by pkbullock** [comment]
This would be an awesome example, been wanting to learn/investigate more about this approach myself. 

If you can submit a sample that would be awesome. 

Also, if you interested, @LuiseFreese runs the PnP Tech Community blog, you could consider to submit a blog post on your findings/good and bad points as well.

**Comment by kasperbolarsen** [comment]
Initial revision read in PR :-)

**Comment by pkbullock** [comment]
Closing as done :-)
