### ISSUE TITLE
CLI Version for Create bulk dummy documents in SharePoint Document library

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#206]
Add CLI version for:
https://pnp.github.io/script-samples/create-dummy-docs-in-library/README.html?tabs=pnpps

**Comment by Jitenparmar** [comment]
Can you please assign this to me?

**Comment by pkbullock** [comment]
Hi @Jitenparmar - I'm going to release for others to contribute to, please let us know if you are planning on working on this one :-)
