### ISSUE TITLE
Add CLI for Microsoft 365 to Get All Apps From The App Catalog And Export It To CSV

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#214]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-get-all-apps-from-appcatalog/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
Assign to me

**Comment by Adam-it** [comment]
take

**Comment by pkbullock** [comment]
Closing as this one is also live - thank you @Adam-it
