### ISSUE TITLE
Add CLI for Microsoft 365 to Delete a library exceeding the list threshold limit. Remove the files and folders before deleting the library

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#215]
Add CLI for Microsoft 365 equivalent 👨‍💻 -
https://pnp.github.io/script-samples/spo-remove-large-library/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
take

**Comment by pkbullock** [comment]
This one is complete and live. Closing. Thank you @Adam-it
