### ISSUE TITLE
CLI version of Create SharePoint Groups in Bulk using CSV file

### ISSUE THREAD

**Issue by ValerasNarbutas** [pnp/script-samples#223]
Hey, i add CLI version for this one Create SharePoint Groups in Bulk using CSV file

**Comment by ValerasNarbutas** [comment]
damn, probably forgot i tried to do this before :(
its not possible with CLI yet, you knew @pkbullock  right? :)

**Comment by pkbullock** [comment]
Ah no I didn't. Slightly misleading title I may have assumed 365 groups. Sorry about that and thank you for confirming.
