### ISSUE TITLE
Sample Site card links are pointing to the wrong pages

### ISSUE THREAD

**Issue by Ryan365Apps** [pnp/script-samples#228]
In some cases, the cards shown don't link to the correct page when filtered

https://pnp.github.io/script-samples/?query=sharepoint

For example:
The first card
![image](https://user-images.githubusercontent.com/50838643/152320001-d15532ee-9ba9-4c5d-a9a9-43c2ef1bb8ff.png)
links to this page
https://pnp.github.io/script-samples/flow-runs-status-list-dashboard/README.html?tabs=cli-m365-ps

**Comment by pkbullock** [comment]
Thank you for the spotting this, I have managed to reproduce the problem.

**Comment by pkbullock** [comment]
@Ryan365Apps  thanks for raising this, this should now be fixed - I'm closing this issue.
