### ISSUE TITLE
wrong tech selected

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#255]
hi @pkbullock 
I was looking for new samples I could rewrite using CLI and I noticed this one
https://pnp.github.io/script-samples/graph-download-office-documents-as-pdf/README.html?tabs=pnpps
I don't think this actually uses PnP.PowerShell 🤔 right? 
Maybe we could select some different tech for it? maybe something like MS graph 🤔

**Comment by pkbullock** [comment]
You're right its just PowerShell, no library used here. Thanks for spotting this one.

In reference to looking for samples ideas, I have a report you might find useful (needs polishing) but it lists out the cmdlet usage for PnP PowerShell, CLI for M365 and shows what is and isnt used in all of the samples. 

Report: [https://pnp.github.io/script-samples/cmdusage.html](https://pnp.github.io/script-samples/cmdusage.html)

I've started to use this, for scripts I've written in the past to increase coverage.

**Comment by Adam-it** [comment]
Wow the report page is amazing 🤩. Thanks for sharing. 👍
Totally will be helpful to get some inspiration on some new samples to show what is possible. 
For example I see still have much to show in terms of yammer or Todo.

**Comment by pkbullock** [comment]
Closing this one as it is complete.
