### ISSUE TITLE
CLI version for Testing user preferred language of SharePoint site

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#267]
👋 hi,
 The aim 🎯 of this issue is to add CLI for M365 version for the script 👉https://pnp.github.io/script-samples/user-language-for-site/README.html?tabs=pnpps

**Comment by Adam-it** [comment]
Assign to me,
take,
take action,
... I really forgot the magic word 🤔😜. pretty please assign me to this issue 🤔

**Comment by pkbullock** [comment]
Hi Adam, I have added permissions for you to manage issues, you are a regular contributor so happy to elevate you :-) so you can assign to yourself, the plugin will be disabled its too flaky.

**Comment by Adam-it** [comment]
WoW 🤩🤩. Thanks a lot 😁. You rock 👍

**Comment by pkbullock** [comment]
Closing as completed.
