### ISSUE TITLE
CLI for M365 version for script "Apply column format to SharePoint column"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#272]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Apply column format to SharePoint column](https://pnp.github.io/script-samples/spo-apply-column-format/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use [field-set](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-set/) and [field-get](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-get/) command

**Comment by Adam-it** [comment]
@pkbullock I know I could do it myself but I don't want to step in anyone's shoes (I hope there is a saying like this also in English 😅)... anyway I think we could label this as 'good first issue' if you agree 😉. And if anyone will need any help I am always more than happy to do so 😉. And if this will get old (like 2-3 weeks without a take), I will do it myself 🙂

**Comment by pkbullock** [comment]
Thank you @Adam-it - your not stepping on anyones shoes at all, really like what you are doing and thank you for the great sample ideas!

**Comment by Jwaegebaert** [comment]
I can give this one a shot 😄

**Comment by Adam-it** [comment]
@Jwaegebaert you rock 🤩.
All yours 👍
Thanks for your help
