### ISSUE TITLE
CLI for M365 version for script "Copy a library view across multiple libraries in destination site"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#273]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Copy a library view across multiple libraries in destination site](https://pnp.github.io/script-samples/spo-copy-library-view/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:
- [list-view-get](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-view-get/) 
- [list-view-add](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-view-add/) 
- [list-view-set](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-view-set/) 
- [list-list](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-list/)

**Comment by reshmee011** [comment]
I can look into it

**Comment by Adam-it** [comment]
sure 👍 
Can't wait to see the PR. 
You rock 🤩
