### ISSUE TITLE
CLI for M365 version for script "Bulk library generation"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#274]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Bulk library generation](https://pnp.github.io/script-samples/spo-create-bulk-libraries/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:
- [field-add](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-add/)
- [list-add](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-add/)
- [list-view-add](https://pnp.github.io/cli-microsoft365/cmd/spo/list/list-view-add/)

**Comment by milanholemans** [comment]
I'm willing to work on this one.

**Comment by Adam-it** [comment]
thanks @milanholemans 👍
You rock 🤩
