### ISSUE TITLE
CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#275]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Export SharePoint List Data to CSV with attachments](https://pnp.github.io/script-samples/spo-export-sharepoint-list-items-to-csv/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [field-get](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-get/)
- [listitem-get](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-get/)
- [file-get](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-get/)

**Comment by nanddeepn** [comment]
Hi @Adam-it, @pkbullock 
Can I work on this?

**Comment by pkbullock** [comment]
Sure, thank you, I'll assign it to you.
