### ISSUE TITLE
CLI for M365 version for script "Get SharePoint List Fields With Required properties And Export It To CSV"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#276]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Get SharePoint List Fields With Required properties And Export It To CSV](https://pnp.github.io/script-samples/spo-get-and-export-list-fields/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [field-get](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-get/)

**Comment by nanddeepn** [comment]
Hi @Adam-it, @pkbullock 
Can I work on this?

**Comment by pkbullock** [comment]
Go for it, I'll assign to you :-)

**Comment by Adam-it** [comment]
@nanddeepn you rock 🤩
