### ISSUE TITLE
CLI for M365 version for script "Run A Search Query And Export To CSV"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#278]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Run A Search Query And Export To CSV](https://pnp.github.io/script-samples/spo-search-export-to-csv/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:
- [search](https://pnp.github.io/cli-microsoft365/cmd/spo/spo-search/)

**Comment by SmitaNachan** [comment]
Hi @Adam-it, @pkbullock 
Can I work on this?

**Comment by Adam-it** [comment]
@SmitaNachan all yours. Thanks for your help! 
You rock 🤩
