### ISSUE TITLE
CLI for M365 version for script "Fetch User Profile Properties From Site Collection And Export To CSV"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#279]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Fetch User Profile Properties From Site Collection And Export To CSV](https://pnp.github.io/script-samples/fetch-user-profile-properties/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:
- [user-get](https://pnp.github.io/cli-microsoft365/cmd/spo/user/user-get/)
- [userprofile-get](https://pnp.github.io/cli-microsoft365/cmd/spo/userprofile/userprofile-get/)

**Comment by MathijsVerbeeck** [comment]
@pkbullock I could work on this one

**Comment by pkbullock** [comment]
Absolutely! Thank you!

**Comment by MathijsVerbeeck** [comment]
@Adam-it  @pkbullock  This issue may be closed I think

**Comment by Adam-it** [comment]
Closing this one as it was already done some time ago 🙂. Seem like an leftover issue 🤔.
Once again thanks @MathijsVerbeeck for you awesome work 🤩🤩
