### ISSUE TITLE
CLI for M365 version for script "Create bulk dummy documents, including minor/major versions, in SharePoint Document library"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#280]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Create bulk dummy documents, including minor/major versions, in SharePoint Document library](https://pnp.github.io/script-samples/create-dummy-docs-versions-in-library/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [folder-add](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-add/)
- [file-add](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-add/)
- [file-checkin](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-checkin/)
- [file-checkout](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-checkout/)

**Comment by MathijsVerbeeck** [comment]
@pkbullock I could work on this one 😄

**Comment by Adam-it** [comment]
I don't see why not 😉. Assigned ✅
Thank you for your help 👍
You rock 🤩
