### ISSUE TITLE
CLI for M365 version for script "Reset files permissions unique to Inherited"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#281]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Reset files permissions unique to Inherited](https://pnp.github.io/script-samples/reset-files-permission-unique-to-inherited/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [folder-get](https://pnp.github.io/cli-microsoft365/cmd/spo/folder/folder-get/)
- [listitem-get](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-get/)
- [listitem-roleinheritance-reset](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-roleinheritance-reset/)

**Comment by nanddeepn** [comment]
Can I work on this?

**Comment by Adam-it** [comment]
sure.
@nanddeepn thanks for your work 👍. You rock 🤩
Assigned ✔
