### ISSUE TITLE
🆕CLI for M365 new sample script idea - move a SharePoint list and its contents from one tenant to another

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#285]
🎯Aim
The aim of this issue would be to add a totally new sample script that will migrate a SharePoint list and it's contents from one tenant to another. Use [CLI for M365](https://pnp.github.io/cli-microsoft365/)

🤔Things to consider
We should consider not only transferring list, columns, and data but also all possible options a user may set considering also the permissions.

**Comment by ValerasNarbutas** [comment]
@Adam-it  this one interesting also, i can take it

**Comment by Adam-it** [comment]
Nice 👍👍
You rock 🤩
Assigned

**Comment by Adam-it** [comment]
@ValerasNarbutas any update on this issue? 🙂
Are you still working on it? If you are blocked on some level maybe you want to bring the problem up and we could recheck/rediscuss it here? 🤔
Or if you currently are unable to continue this one maybe we could open this up for someone else? 👍

**Comment by pkbullock** [comment]
Hi @ValerasNarbutas - unassigning this one, please let us know if you would like to work on this one. Thank you. 😁

**Comment by Adam-it** [comment]
@pkbullock as this does not seem to draw much attention, and I would not like to create issues on your repo that just are never resolved I will assign myself to this one and try to resolve this in the coming month. 💪
Sorry for creating clutter and thank you for your patience  🙏
