### ISSUE TITLE
New sample script idea - Clone a Planner plan

### ISSUE THREAD

**Issue by milanholemans** [pnp/script-samples#296]
Idea is to create a script that clones a Planner plan. It will create a new plan, buckets and tasks based on a template plan. This is currently possible via the UI, but not by code as far as I know.

**Comment by milanholemans** [comment]
If this is ok, I'd like to work on this.

**Comment by Adam-it** [comment]
@milanholemans do you plan to add CLI version of this 👀?

**Comment by milanholemans** [comment]
> @milanholemans do you plan to add CLI version of this 👀?

Yes, first version of the script will be for CLI. The PnP.PowerShell version will follow later.
