### ISSUE TITLE
[Bug] CLI M365 samples - `m365 status` invalid condition check

### ISSUE THREAD

**Issue by Jwaegebaert** [pnp/script-samples#298]
When we use CLI for Microsoft 365 within PowerShell we shouldn't forget to convert our output to an object. Most samples start off by doing a `m365 status` check to see if they are still logged in to their Microsoft 365 environment. Which looks something like this.

``` powershell
$m365Status = m365 status
if ($m365Status -eq "Logged Out") {
    m365 login
}
```

The if condition here will always be false because we aren't converting the output of `m365 status` to an object. 

![afbeelding](https://user-images.githubusercontent.com/38426621/171829213-8c66ce0e-80f9-4fb6-a469-c0f098199905.png)

To solve this we need to use `ConvertFrom-Json` after the status command. Then the login logic would look like this.

``` powershell
$m365Status = m365 status | ConvertFrom-Json
if ($m365Status -eq "Logged Out") {
    m365 login
}
```

This will ensure that our output is converted to a usable variable within PowerShell.

![afbeelding](https://user-images.githubusercontent.com/38426621/171829714-7dc3b9d8-870b-4ccb-9798-7b8336c47417.png)

This issue applies to the following samples:

- aad-analyze-users-hibp
- aad-delete-m365-groups-and-sharepoint-sites
- aad-replace-membership-of-selected-groups
- aad-replace-owner-with-a-different-one
- bulk-undelete-from-recyclebin
- create-comm-sites-specific-locale
- flow-runs-day-summary
- flow-runs-status-list-dashboard
- generate-markdown-lcids
- get-all-site-collections-subwebs
- planner-migration-spo-list
- remove-delete-option-library
- report-private-teams-excel
- spo-add-document-library-webpart-to-page
- spo-add-multiple-lists-in-multiple-sites
- spo-export-sharepoint-list-items-to-csv
- spo-add-site-design-with-custom-list
- spo-add-tenant-theme
- spo-cleanup-site-column-usage
- spo-copy-files-to-another-library
- spo-export-data-to-sharepoint-lists
- spo-export-site-usage-reports
- spo-generate-demo-events
- spo-get-all-apps-from-appcatalog
- spo-get-lists-libraries-item-count-permissions
- spo-group-permission-report
- spo-list-items-large-lists
- spo-list-items-with-caml-query
- spo-list-site-collection-lists
- spo-list-site-collection-owners
- spo-list-site-externalusers
- spo-recyclebin-items-to-csv
- spo-remove-large-library
- spo-replace-site-collection-admin
- spo-set-home-site
- spo-setup-example-site
- spo-upload-local-files-and-folder
- teams-add-bulk-users-teams
- teams-create-team-and-add-members-and-owners
- teams-teams-export-teams-information
- teams-full-report
- teams-install-personal-app
- teams-list-all-tabs-teams
- teams-list-all-teammembers-teams
- teams-list-teams-owners-and-members
- teams-remove-personal-app
- teams-share-socialchampion
- user-language-for-site

**Comment by Jwaegebaert** [comment]
I am willing to work on this one.

**Comment by Adam-it** [comment]
@Jwaegebaert good catch 👍👍
you rock 🤩

**Comment by pkbullock** [comment]
This is quite wide spread - thank you for looking at this, I don't typically check the scripts - perhaps something I should start to do. Appreciate yours and @Adam-it help. Let me know if you need any support. 

I will list any new samples that show this pattern - it seems like quite a few folks use that pattern.

**Comment by pkbullock** [comment]
Another method (after checking to see how widespread this is) is using "-Match" instead of "-eq". Would this be an easier change?

![image](https://user-images.githubusercontent.com/8781041/172067138-45e0aaf7-24f3-4743-8a47-52432a2b00e8.png)

I saw this btw in an article I read recently: https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/monitor-and-notify-m365-health-using-cli-for-microsoft-365/ba-p/3000703

**Comment by Adam-it** [comment]
or another way is by adding the output mode to text how it was before by default 😉. TBH the origin of this bug (that's what I suspect as I am also one of the contributors that used this approach extensively at the time 😋) is that in CLI repo we introduced a breaking change here 👉 https://github.com/pnp/cli-microsoft365/pull/2602.
The default output mode started to be json not text which actually broke this condition 😉. 
When we would retrieve the `status` as `text` this will actually work like before. 
![image](https://user-images.githubusercontent.com/58668583/172070439-9de9dc04-435c-4e67-b75b-691a08d6b3aa.png)

so a another way of fixing this may also be to add `--output text` to every place 👍.
also at the same time we could update in the `sample.json` file the CLI version to latest 🤔 as for example here https://github.com/pnp/script-samples/blob/main/scripts/flow-runs-day-summary/assets/sample.json we have version `3.7.0` of CLI for M365 which (TBH I don't remember so it's a bit lucky guess 😉) probably back then still had `--output text` as default 🤔.

so to sum up:
- For sure the latest CLI output mode is different so this logic does not work 😉. Thanks @Jwaegebaert for having a sharp eye 🙂 You rock 🤩
- For sure we may fix it by one of the 3 ways: converting, different way of comparing in ps1 or changing the default output mode. I suppose each option is ok 🙂
- For sure at the same time of the fix I believe we should also update the CLI version in sample.json to latest to be consistent

@Jwaegebaert please do consider my comment. 
Thanks @pkbullock for additional analysis on this issue. You rock as well 🤩🤩.

In future I will try to be more thoughtful of script samples when there is some braking change in CLI for M365 introduced 🤔. TBH I forgot this change may effect many script samples we have and may give the users which will be using them with latest version a buggy experience 😔. Sorry for that 🙏 
Let me know if you need any help working on this 🙂.

**Comment by Jwaegebaert** [comment]
Good point to check the CLI for M365 version within the `sample.json` files. The default output change happened as of v4. I do think it is interesting to keep the last tested version of the sample. 
If we use the `-match` comparison, as @pkbullock suggested, we capture all the output types. With this, we won't need to update the version of CLI for M365.
