### ISSUE TITLE
CLI for M365 version for script "SharePoint Modern Page Publishing Report"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#305]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [SharePoint Modern Page Publishing Report](https://pnp.github.io/script-samples/spo-modern-page-publishing-report/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [listitem-list](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-list/)
- or [page-list](https://pnp.github.io/cli-microsoft365/cmd/spo/page/page-list/)
- or mix of both 😉

**Comment by nanddeepn** [comment]
Hi @Adam-it, @pkbullock 
Can I work on this?

**Comment by Adam-it** [comment]
@nanddeepn all yours 👍👍
