### ISSUE TITLE
CLI for M365 version for script "Set Home site for SharePoint tenant"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#306]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Set Home site for SharePoint tenant](https://pnp.github.io/script-samples/spo-set-home-site/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [homesite-set](https://pnp.github.io/cli-microsoft365/cmd/spo/homesite/homesite-set/)

**Comment by SmitaNachan** [comment]
Hi,
Can I work on it?

**Comment by Adam-it** [comment]
@SmitaNachan all yours 👍👍👍.
Thanks for stepping up 😍 you rock 🤩
