### ISSUE TITLE
CLI for M365 version for script "Bulk Create Teams with JSON File"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#307]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Bulk Create Teams with JSON File](https://pnp.github.io/script-samples/teams-bulk-create-teams/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [o365group-add](https://pnp.github.io/cli-microsoft365/cmd/aad/o365group/o365group-add/)
- [site-get](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-get/)

**Comment by nanddeepn** [comment]
Hi @Adam-it, @pkbullock 
Can I work on this?

**Comment by Adam-it** [comment]
Sold 😊
