### ISSUE TITLE
CLI for M365 version for script "Reports to Excel where the specified Term is used" 

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#308]
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Reports to Excel where the specified Term is used](https://pnp.github.io/script-samples/ReportTermUse/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [listitem-get](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-get/)
- [listitem-list](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-list/)
- [field-list](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-list/)

**Comment by ValerasNarbutas** [comment]
@Adam-it  i will take on this one

**Comment by Adam-it** [comment]
Cool 👍. Thanks @ValerasNarbutas .
You rock 🤩

**Comment by Adam-it** [comment]
@ValerasNarbutas any update on this issue? 🙂
Are you still working on it? If you are blocked on some level maybe you want to bring the problem up and we could recheck/rediscuss it here? 🤔
Or if you currently are unable to continue this one maybe we could open this up for someone else? 👍

**Comment by pkbullock** [comment]
Hi @ValerasNarbutas - I'm going to unassign it to allow others to contribute to this, please let us know if you are working on this :-)

**Comment by Adam-it** [comment]
I guess no pressure 👍. This is open source after all so we do it when/if we can 😉. 
You are awesome 🤩

**Comment by Adam-it** [comment]
@pkbullock as this does not seem to draw much attention, and I would not like to create issues on your repo that just are never resolved I will assign myself to this one and try to resolve this in the coming month. 💪
Sorry for creating clutter and thank you for your patience  🙏
