### ISSUE TITLE
Check the breakpoint CSS for the cards - smaller view there is some overlapping

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#315]
![image](https://user-images.githubusercontent.com/8781041/173766945-f8bbb6cb-ed6f-4722-af00-740e49560a76.png)

**Comment by ValerasNarbutas** [comment]
Hey, @pkbullock , 
i just looked as of curiosity to this one, i have to say i was not able to overlap like you did on any size. Was using Chrome to test.
Are you sure it is an issue?

**Comment by ValerasNarbutas** [comment]
i was wrong, on 1076 width it was overlapping.

**Comment by pkbullock** [comment]
Closing as new update on issue in issue #510 seems the issue has resurfaced.
