### ISSUE TITLE
Sample Update - PnP PowerShell - Add a document library web part to a page

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#325]
This sample is using the older cmdlets, update will be needed:
https://pnp.github.io/script-samples/spo-add-document-library-webpart-to-page/README.html 

Older cmdlets:
Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-PnPClientSideText, Add-PnPClientSideWebPart, Get-PnPClientSidePage

**Comment by ToddKlindt** [comment]
Pull request, https://github.com/pnp/script-samples/pull/342

**Comment by pkbullock** [comment]
Closing as completed
