### ISSUE TITLE
Update needed - SPO Management Shell - Create and add list template to SharePoint site

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#326]
Example: https://pnp.github.io/script-samples/spo-add-list-template-with-custom-library/README.html?tabs=spoms-ps

 Get-SPOListDesign - no longer exists, the sample will break with the latest version of SPO Management Shell.

Reference to use: https://docs.microsoft.com/en-us/sharepoint/lists-custom-template

**Comment by pkbullock** [comment]
Hi @Jitenparmar - will you be working on this one or can I release to the community?

**Comment by Jitenparmar** [comment]
Hello, @pkbullock apologies for the delay I will complete this by this weekend. Thanks for the reminder.

**Comment by Jitenparmar** [comment]
@pkbullock I am not able to find the first link? is it removed from the script samples?

**Comment by kasperbolarsen** [comment]
@Jitenparmar the link seems to work just fine for me

**Comment by reshmee011** [comment]
@pkbullock : The cmd Get-SPOListDesign  is present from the doc https://docs.microsoft.com/en-us/sharepoint/lists-custom-template
<img width="628" alt="image" src="https://user-images.githubusercontent.com/7693852/230277144-f54026cd-db51-4f73-9561-573fae4c8c84.png">

I think the issue can be closed.

**Comment by pkbullock** [comment]
Closing :-)
