### ISSUE TITLE
How to save Stream videos CSV report?

### ISSUE THREAD

**Issue by rajaseg** [pnp/script-samples#340]
I want to export the Stream videos to a CSV file. When I run the below script the results are displayed in the command prompt. How to export the results to the CSV file.

https://pnp.github.io/script-samples/stream-report-videos/README.html?tabs=pnpps2

![image](https://user-images.githubusercontent.com/633479/181016151-a14cbf97-e076-472f-9527-cc9404eec0dc.png)

**Comment by Jwaegebaert** [comment]
At the start of the `PnP PowerShell Alternative` sample you can adjust the parameter `OutputCsvFileName`  to true. That should output your result to a CSV file.

For example: If save the script to a new file named `example.ps1`. When you want to execute it and change the parameter `OutputCsvFileName` to true you could run the following command: `.\example1.ps1  -OutputCsvFileName $true`. This should execute the script and generate you a CSV file.

Hope this helps.

**Comment by rajaseg** [comment]
> At the start of the `PnP PowerShell Alternative` sample you can adjust the parameter `OutputCsvFileName` to true. That should output your result to a CSV file.
> 
> For example: If save the script to a new file named `example.ps1`. When you want to execute it and change the parameter `OutputCsvFileName` to true you could run the following command: `.\example1.ps1 -OutputCsvFileName $true`. This should execute the script and generate you a CSV file.
> 
> Hope this helps.

@Jwaegebaert, Thank you very much for the tip. Everything is working as expected.

**Comment by rajaseg** [comment]
> > At the start of the `PnP PowerShell Alternative` sample you can adjust the parameter `OutputCsvFileName` to true. That should output your result to a CSV file.
> > For example: If save the script to a new file named `example.ps1`. When you want to execute it and change the parameter `OutputCsvFileName` to true you could run the following command: `.\example1.ps1 -OutputCsvFileName $true`. This should execute the script and generate you a CSV file.
> > Hope this helps.
> 
> @Jwaegebaert, Thank you very much for the tip. Everything is working as expected.

@Jwaegebaert, Is it possible to use the session already open for login purpose?

**Comment by Jwaegebaert** [comment]
@rajaseg, could you please clarify what you mean with an already open session?

**Comment by rajaseg** [comment]
> @rajaseg, could you please clarify what you mean with an already open session?

@Jwaegebaert, When we run the script, it will pop up the login screen for Microsoft Stream? Is it possible to use the session If I already connected to Microsoft Stream?

**Comment by Jwaegebaert** [comment]
Not to my knowledge. Maybe @teamneroblanco can give more insight towards your question.

**Comment by rajaseg** [comment]
> Not to my knowledge. Maybe @teamneroblanco can give more insight towards your question.

@teamneroblanco, can you give your insight on the issue?
