### ISSUE TITLE
New sample script idea - Retrieve AAD delegated / application permission for MS App

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/script-samples#344]
I didn't found anything related to this, so here's my suggestion. Based on the permission name ("Sites.Read.All"), the Microsoft App ("Microsoft Graph" / "SharePoint Online" / ...) and the permission type ("Application" / "Delegated"), the script would be able to retrieve info about permissions.

The script would accept partial permission name info, like "Sites.Read" or even just "Read", then would display matching results.

If it's relevant here, I'd like to submit it, using CLI for Microsoft 365 (in PowerShell) and Microsoft Graph PowerShell.

**Comment by pkbullock** [comment]
Yes please, sounds like an awesome sample 😃
