### ISSUE TITLE
Getting  "ExecuteQuery" with "0" argument(s): "Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetById FieldLinks 

### ISSUE THREAD

**Issue by elimigdal** [pnp/script-samples#350]
my case is that my TITLE is "not required" + i have removed it from the default view + removed it from the "columns" of the new button ( by using edit column)

would love a solution
thanks

**Comment by pkbullock** [comment]
Please can you describe the script you are referring to?

**Comment by pkbullock** [comment]
Closing as no response.
