### ISSUE TITLE
CLI for M365 version for script "Export Term Store terms to CSV"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#359]
## 🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Export Term Store terms to CSV](https://pnp.github.io/script-samples/spo-export-termstore-terms-to-csv/README.html?tabs=pnpps).

## 🤔How
I think one of the best approach would be to use 
- [spo term list](https://pnp.github.io/cli-microsoft365/cmd/spo/term/term-list/)
- [spo term group list](https://pnp.github.io/cli-microsoft365/cmd/spo/term/term-group-list/)
- [spo term set list](https://pnp.github.io/cli-microsoft365/cmd/spo/term/term-set-list/)
- `output csv`

**Comment by reshmee011** [comment]
Please assign to me.
