### ISSUE TITLE
Compare document in two tenants

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#36]
Perform a hash check or file size between a migrated file in two tenants

**Comment by dips365** [comment]
Could you please assign to me ?

**Comment by ValerasNarbutas** [comment]
@dips365 hope you don't mind i will upload this sample.

**Comment by pkbullock** [comment]
@ValerasNarbutas - this has been there a while, feel free to take over 😃

**Comment by pkbullock** [comment]
Closing as complete
