### ISSUE TITLE
Pnp Powershell script for creating a Quick Links web part from a SharePoint List

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#360]
Creating a page and configure the Quick Links web part and then use the PnP provisioning tool to deploy it where needed is pretty easy. However updating an existing Quick Links web part or creating it based on a reference list/csv or similar is a royal pain in the neck.
This script will provide a basic setup for creating the web part on the fly using a SharePoint list as a data provider

**Comment by pkbullock** [comment]
ref #362 complete and closing.
