### ISSUE TITLE
Sample showing how to ensure that office docs will open in the client rather than the browser 

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#369]

**Comment by kasperbolarsen** [comment]
@pkbullock   this idea is too similar to https://pnp.github.io/script-samples/spo-activate-site-feature to add it as a new sample, doen't you agree?

**Comment by pkbullock** [comment]
Hi

Although similar, they do very different things. I'd add as new sample.

Paul

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kasperbolarsen** [comment]
OK, added :-)

Kasper
