### ISSUE TITLE
PnP Script reset-files-permission-unique-to-inherited throws list exceeds threshold for large libraries

### ISSUE THREAD

**Issue by reshmee011** [pnp/script-samples#373]
PnP PowerShell script reset-files-permission-unique-to-inherited throws list exceeds threshold for large libraries. I have an alternate version to work with large libraries
`
try
{
   Get-PnPListItem -List $ListName -PageSize 2000 | Where {$_.FieldValues.FileRef -like "$FolderServerRelativePath*" -and $_.FileSystemObjectType -eq "File" } | ForEach-Object {
     $hasUniqueRole = Get-PnPProperty -ClientObject $_ -Property HasUniqueRoleAssignments
            if($hasUniqueRole -eq $true){
                Write-host $_.FieldValues.FileRef
                Write-host "Reset Permisison starting for file with id $($_.Id)" -ForegroundColor DarkGreen
                $_.ResetRoleInheritance()
                $_.update()
                $Context.ExecuteQuery()
             }
    }
}
catch {
    write-host "Error: $($_.Exception.Message)" -foregroundcolor Red
}

`
@pkbullock , would you recommend refactoring the current code to work with large libraries or shall I add a new scenerio?

**Comment by ValerasNarbutas** [comment]
@pkbullock  i can refactor this one to work with large libs

**Comment by reshmee011** [comment]
I forgot to catch up on this one, @ValerasNarbutas , thanks for enquiring about it:)

**Comment by ValerasNarbutas** [comment]
> I forgot to catch up on this one, @ValerasNarbutas , thanks for enquiring about it:)

no problem, the update was added to the script. Works well with 5000+ folders in the library.

**Comment by ValerasNarbutas** [comment]
Hey @reshmee011 , issue can be closed! :)

**Comment by reshmee011** [comment]
@ValerasNarbutas : Awesome the PnP PowerShell seems to be fixed, Has the m365 CLI script tested against 5k+ folders?

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas : Awesome the PnP PowerShell seems to be fixed, Has the m365 CLI script tested against 5k+ folders? 

Oh, good point. I will test it. Hold this open for now :)

**Comment by ValerasNarbutas** [comment]
@reshmee011 i have checked CLI script, all is good for a large number of items, i found one bug but not related to a number of items, and added adjustment.

**Comment by reshmee011** [comment]
@ValerasNarbutas : Amazing , thank you for checking the m365 CLI even it was not in the original scope of the issue. I am closing the issue.
