### ISSUE TITLE
Bug: Language tab has inconsistent naming of `CLI for Microsoft 365`

### ISSUE THREAD

**Issue by garrytrinder** [pnp/script-samples#381]
I've seen this on the sample https://pnp.github.io/script-samples/todo-cleanup-completed-todos/README.html?tabs=m365cli-bash

The PowerShell tab is named correctly, however the bash tab is incorrect, it displays `Microsoft 365 CLI with bash` but should be CLI for Microsoft 365 with bash`. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11563347/196902312-649b459b-27d6-4b3c-aa3b-710f4b4ed4e1.png">

**Comment by pkbullock** [comment]
I'm fired lol, I'll update on my next contribution window. 😎
