### ISSUE TITLE
Idea: Iterate all site collections and create report about template, lockstate, groupid, LastModified etc

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#391]
Hi, I have looked for an existing sample for such a inventory but so far haven't found one

**Comment by pkbullock** [comment]
Hi Kasper, sorry I missed this, looks like an awesome sample idea. :-)

**Comment by kasperbolarsen** [comment]
Ready for review :-)

**Comment by pkbullock** [comment]
Closing as this was kindly completed :-)
