### ISSUE TITLE
Clean up duplicate CLI samples from original repo

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#398]
Look to remove any CLI sample that was used to seed the Script Samples repo in the beginning. 

Paul has a list

Provide link to the sample in the original repo instead where a sample contain multiple samples for a scenario. With a relocation blurb. 

Cc: @Adam-it feel free to add anything I may have missed for tracking.

**Comment by pkbullock** [comment]
Hi some stats on the scale of the change: 

We currently use 61 samples from the CLI repo originally imported mid-last year,  today, 18 of those have more that one script associated with them, for those I will be removing just the CLI Powershell/bash with a link to your repo and some blurb explaining the move. 

So just as an FYI, 43 samples will be deleted and converted to "ideas" in issues list for the other tools to implement. That way I can preserve all contributions without loss. 

Note: users hitting those samples remaining will get an extra hop to the CLI repo (not the end of the world) - but this will stop others from contributing again in the scenario that exists elsewhere.

We do have a gap, for the 18 that have alternatives, to avoid the appearance of duplicates, we need to shift the titles of those samples to enable others to differentiate them in the adoption.microsoft.com gallery, most likely on my side.

**Comment by Adam-it** [comment]
All fine for me, except that I think we should change title for that 18 samples on CLI side to indicate those are only CLI versions. Those coming from script sample maybe done in multiple tech.

@pnp/cli-for-microsoft-365-maintainers any additional comments?

**Comment by pkbullock** [comment]
Hi @Adam-it, I have a branch waiting with the changes to remove the imported CLI Samples as discussed. 
Paolo said it should take 24 hours to disappear from the adoption gallery, also if you CLI extension consumes this, then that too will be reduced.

The changes:

# Updates to remove JUST the CLI for Microsoft 365 sample from the scenario

https://pnp.github.io/script-samples/spo-add-app-catalog/README.html
https://pnp.github.io/script-samples/spo-add-multiple-folders-in-libraries-using-csv-file/README.html
https://pnp.github.io/script-samples/spo-empty-tenant-recyclebin/README.html
https://pnp.github.io/script-samples/spo-hide-list-from-site-contents/README.html
https://pnp.github.io/script-samples/spo-list-site-externalusers/README.html
https://pnp.github.io/script-samples/spo-list-tenant-wide-extensions/README.html
https://pnp.github.io/script-samples/spo-remove-custom-themes/README.html
https://pnp.github.io/script-samples/spo-remove-orphaned-redirect-sites/README.html
https://pnp.github.io/script-samples/spo-remove-site-designs/README.html
https://pnp.github.io/script-samples/spo-remove-site-scripts/README.html
https://pnp.github.io/script-samples/spo-setup-example-site/README.html
https://pnp.github.io/script-samples/teams-list-teams-owners-and-members/README.html
https://pnp.github.io/script-samples/aad-delete-m365-groups-and-sharepoint-sites/README.html
https://pnp.github.io/script-samples/aad-delete-m365-groups/README.html
https://pnp.github.io/script-samples/aad-replace-membership-of-selected-groups/README.html
https://pnp.github.io/script-samples/aad-replace-owner-with-a-different-one/README.html
https://pnp.github.io/script-samples/flow-export-all-flows-in-environment/README.html
https://pnp.github.io/script-samples/flow-runs-day-summary/README.html

# Removed entirely

https://pnp.github.io/script-samples/spo-add-custom-clientside-webpart-to-modern-page/README.html
https://pnp.github.io/script-samples/spo-add-site-collection-admin-using-csv-file/README.html
https://pnp.github.io/script-samples/spo-copy-files-to-another-library/README.html
https://pnp.github.io/script-samples/spo-delete-non-group-connected-modern-sites/README.html
https://pnp.github.io/script-samples/spo-disable-tenant-wide-extension/README.html
https://pnp.github.io/script-samples/spo-ensure-siteassets-library/README.html
https://pnp.github.io/script-samples/spo-grant-api-permissions-aad/README.html
https://pnp.github.io/script-samples/spo-insert-sp-library-pictures-into-word/README.html
https://pnp.github.io/script-samples/spo-list-all-application-customizers/README.html
https://pnp.github.io/script-samples/spo-list-site-app-catalogs/README.html
https://pnp.github.io/script-samples/spo-list-site-collection-lists/README.html
https://pnp.github.io/script-samples/spo-list-site-collection-owners/README.html
https://pnp.github.io/script-samples/spo-monitor-site-collection-storage-usage/README.html
https://pnp.github.io/script-samples/spo-remove-sitecollection-admin-user/README.html
https://pnp.github.io/script-samples/spo-replace-site-collection-admin/README.html
https://pnp.github.io/script-samples/spo-sync-splib-into-az-storage-container/README.html
https://pnp.github.io/script-samples/spo-upload-local-files-and-folder/README.html
https://pnp.github.io/script-samples/teams-add-bulk-users-teams/README.html
https://pnp.github.io/script-samples/teams-create-team-and-add-members-and-owners/README.html
https://pnp.github.io/script-samples/teams-create-team-from-group/README.html
https://pnp.github.io/script-samples/teams-deploy-teams-app/README.html
https://pnp.github.io/script-samples/teams-export-teams-conversations/README.html
https://pnp.github.io/script-samples/teams-govern-orphan-teams/README.html
https://pnp.github.io/script-samples/teams-install-personal-app/README.html
https://pnp.github.io/script-samples/teams-list-all-tabs-teams/README.html
https://pnp.github.io/script-samples/teams-list-teams-app-usage/README.html
https://pnp.github.io/script-samples/teams-remove-personal-app/README.html
https://pnp.github.io/script-samples/teams-remove-wikitab-teams/README.html
https://pnp.github.io/script-samples/aad-analyze-user-profile-photos/README.html
https://pnp.github.io/script-samples/aad-flag-groups-with-user-names/README.html
https://pnp.github.io/script-samples/aad-manage-group-users/README.html
https://pnp.github.io/script-samples/flow-cancel-all-running-flow-runs/README.html
https://pnp.github.io/script-samples/flow-export-flow-logicapp/README.html
https://pnp.github.io/script-samples/flow-inventory-flows-by-author/README.html
https://pnp.github.io/script-samples/flow-resubmit-all-failed-flow-runs/README.html
https://pnp.github.io/script-samples/flow-search-flows-for-connection/README.html
https://pnp.github.io/script-samples/todo-cleanup-completed-todos/README.html
https://pnp.github.io/script-samples/tenant-monitor-notify-healthstatus/README.html
https://pnp.github.io/script-samples/spo-add-multiple-lists-in-multiple-sites/README.html
https://pnp.github.io/script-samples/spo-list-failed-sitedesigns/README.html
https://pnp.github.io/script-samples/teams-list-all-teammembers-teams/README.html
https://pnp.github.io/script-samples/teams-recognize-most-active-users-specific-team/README.html
https://pnp.github.io/script-samples/teams-share-socialchampions/README.html

**Comment by Adam-it** [comment]
Wow. You rock 🤩
Unfortunately I am not ready on the CLI side with the needed changes yet. 
I will try to finish it off over the weekend and let you know 👍

**Comment by Adam-it** [comment]
@pkbullock I started working on refactoring samples on CLI side. I will let you know when its done. 
cheers 👍

**Comment by pkbullock** [comment]
Closing as done.

**Comment by pkbullock** [comment]
The GH-Pages branch I think still contains the files, the site is still showing the content despite removing from branch

**Comment by pkbullock** [comment]
Might leave this for now, eventually I would hope this get removed - will check later on.

**Comment by pkbullock** [comment]
Removing Delete all Microsoft 365 groups from GH-Pages Branch as test

**Comment by pkbullock** [comment]
Fixed and closing, this change is now reflecting in the sample gallery in both the site and the adoption sample gallery.
