### ISSUE TITLE
Example scripts processing items greater than 5000 items

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#40]
- Libraries
- Using latest PnP PowerShell (not classic)
- Ideally adding CLI as well

**Comment by ValerasNarbutas** [comment]
hey @pkbullock 
i can add script for using pnp and will check CLI also. Can you assign to me?

**Comment by pkbullock** [comment]
Sure done :-)

**Comment by pkbullock** [comment]
Closing as complete - Thank you!
