### ISSUE TITLE
Idea: script that looks for the People Web part in in a site collection and removes a given user

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#408]

**Comment by kasperbolarsen** [comment]
@pkbullock will "export-spo-people-web-part-users" be a proper title ?

**Comment by pkbullock** [comment]
Can it be "spo-export-people-web-part-users" - i try to group by workload (admittedly not very well) - thank you

**Comment by kasperbolarsen** [comment]
first PR of 2023 :-)

**Comment by pkbullock** [comment]
Happy New Year, I will process this PR this week, :-)

**Comment by pkbullock** [comment]
Merged - Thank you :-)
