### ISSUE TITLE
💡Get a list of Site Collection Admins and Site Owners from list of sites

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#413]
Run through the SharePoint sites and find the Site admins.
These are not the Office 365 Group Connected sites.

**Comment by kasperbolarsen** [comment]
like a slightly modified version of this https://pnp.github.io/script-samples/spo-export-basic-sitecollection-info/README.html?tabs=pnpps ?

**Comment by pkbullock** [comment]
There is another one, please hold off this one. We had to remove some samples for the CLI from the initial creation of this site. 

There was one, only for CLI that is very similar but it needs to be reserected. 

@kasperbolarsen is it ok if I take this one?, to include the original removed sample as well. 

Sorry but messy this example.

**Comment by kasperbolarsen** [comment]
Hi Paul, no problem at all. It was just a suggestion 🙂

**Comment by pkbullock** [comment]
Closing as low activity (lol from me)
