### ISSUE TITLE
💡Apply provisioning template with example of parameters

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#414]
Apply a PnP Provisioning template with use of parameters to control contents.

**Comment by kasperbolarsen** [comment]
Hi Paul, please assign this one to me :-)

**Comment by kasperbolarsen** [comment]
Hi @pkbullock , which name should I use on this, spo-apply-pnptemplate-with-parameters or something like that ?

**Comment by kasperbolarsen** [comment]
Hi @pkbullock , which name should I use on this, spo-apply-pnptemplate-with-parameters or something like that ?

**Comment by pkbullock** [comment]
That is great, apologies I don't always see notifications.

**Comment by kasperbolarsen** [comment]
PR created :-)
