### ISSUE TITLE
💡Enable Site Collection App Catalogs on a specific sites using CSV

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#417]
- Enable this for a list of sites
- Indicate there is a dependency that the user must have access to the app catalog to apply

**Comment by nanddeepn** [comment]
Can I work on this?

**Comment by pkbullock** [comment]
Thank you 😊

**Comment by nanddeepn** [comment]
Hi @pkbullock 

We already have similar script sample - [Add App Catalog to SharePoint site](https://pnp.github.io/script-samples/spo-add-app-catalog/README.html?tabs=spoms-ps)

Should I update this script sample to use CSV input or write a new script sample altogether?
Please suggest.
