### ISSUE TITLE
💡Get Message Centre Announcements and Post to Teams Channel

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#419]
- Get Message Centre Announcements
- Post to Teams Channel

**Comment by pkbullock** [comment]
Completed

**Comment by nanddeepn** [comment]
Nice work @ValerasNarbutas 👏

@pkbullock, can I add the CLI for M365 version of this? We can use [tenant serviceannouncement message list](https://pnp.github.io/cli-microsoft365/cmd/tenant/serviceannouncement/serviceannouncement-message-list/)
Please suggest.

**Comment by ValerasNarbutas** [comment]
> 

i would say sure why not @nanddeepn

**Comment by pkbullock** [comment]
@nanddeepn reopened for recording your idea - thank you!
