### ISSUE TITLE
Locate all Teams having a Wiki and export the list to CSV

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#432]
Similar to https://office365itpros.com/2022/07/15/teams-wiki-nomore/ but using CLI or PnP.PowerShell  :-)

**Comment by kasperbolarsen** [comment]
Perhaps a good first PR for somebody?

**Comment by pkbullock** [comment]
Thanks @kasperbolarsen for the idea and giving the community an opportunity to complete the sample

**Comment by ValerasNarbutas** [comment]
@pkbullock i can do this using Microsoft graph.

**Comment by pkbullock** [comment]
Go for it - thanks!

**Comment by ValerasNarbutas** [comment]
thanks, i will start when ever pull requests merged, dont wanna mix it like last time :)

**Comment by ValerasNarbutas** [comment]
@pkbullock added sample for wiki tabs to csv.
Thanks.

**Comment by ValerasNarbutas** [comment]
This can be closed
