### ISSUE TITLE
Including Pages in the SiteDesign

### ISSUE THREAD

**Issue by eby1212** [pnp/script-samples#436]
Hi Reshmee @reshmee011
Thank you very much for providing  this pretty little script to create site Designs!
https://pnp.github.io/script-samples/spo-add-sitedesign-permissions/README.html?tabs=pnpps
I really appreciate your effort, to make that script public!

But I have a question about it. Do you know if there is a possibilty to include Site Pages into the Site Design?
According to f.e. "Employee onboarding team" Site Design form MSFT this should be possible.

Do you have any idea how to accomplish that? 

Thank you & regards Yannick

**Comment by reshmee011** [comment]
@eby1212 : it is possible to extend the site design to call logic app or power automate linked to an azure function to provision pages. I have not tried, I would within PowerShell apply the site design and then run the script to deploy the pages.

**Comment by ValerasNarbutas** [comment]
> @eby1212 : it is possible to extend the site design to call logic app or power automate linked to an azure function to provision pages. I have not tried, I would within PowerShell apply the site design and then run the script to deploy the pages.

Hi @reshmee011 ,
in this script design is extracted from existing site but this comlet command does not extract sitePages.
It should be posible to update design with actions like:
``json
{
        "verb": "createDocumentLibrary",
        "listName": "Site Pages"
    },
    {
        "verb": "createSitePage",
        "listName": "Site Pages",
        "pageName": "Home",
        "layoutType": "Home",
        "subactions": [
          {
            "verb": "addClientSideWebPart",
            "webPartId": "b7dd04e1-19ce-4b24-9132-b60a1c2b910d",
            "section": 1,
            "column": 1,
            "order": 1
          },
          {
            "verb": "addClientSideWebPart",
            "webPartId": "3c6303c4-9328-4ed5-9d5f-1e494cfe948a",
            "section": 1,
            "column": 2,
            "order": 2
          }
        ]
    },
    {
        "verb": "createSitePage",
        "listName": "Site Pages",
        "pageName": "About Us",
        "layoutType": "Article",
        "subactions": [
          {
            "verb": "addClientSideWebPart",
            "webPartId": "b7dd04e1-19ce-4b24-9132-b60a1c2b910d",
            "section": 1,
            "column": 1,
            "order": 1
          },
          {
            "verb": "addClientSideWebPart",
            "webPartId": "3c6303c4-9328-4ed5-9d5f-1e494cfe948a",
            "section": 1,
            "column": 2,
            "order": 2
          }
        ]
    },
    {
        "verb": "createSitePage",
        "listName": "Site Pages",
        "pageName": "Contact Us",
        "layoutType": "Article",
        "subactions": [
          {
            "verb": "addClientSideWebPart",
            "webPartId": "b7dd04e1-19ce-4b24-9132-b60a1c2b910d",
            "section": 1,
            "column": 1,
            "order": 1
          },
          {
            "verb": "addClientSideWebPart",
            "webPartId": "3c6303c4-9328-4ed5-9d5f-1e494cfe948a",
            "section": 1,
            "column": 2,
            "order": 2
          }
        ]
    }
``
would it be enough? if so i could update this sample.
2

**Comment by reshmee011** [comment]
@eby1212 : It would be amazing if siteDesign supported creation of pages. However, site design does not seem to support provisioning of pages , please refer https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema for more info.
Please refer to a sample script based on PnP PowerShell which I used to export a page from a site to deploy to another site.
https://pnp.github.io/script-samples/spo-provision-homepage/README.html?tabs=pnpps

**Comment by pkbullock** [comment]
Hope this answers your query @eby1212 - closing as answered 😊 thank you @reshmee011 and @ValerasNarbutas for responding to this 😍
