### ISSUE TITLE
Reset permission from Unique permission for SharePoint files.

### ISSUE THREAD

**Issue by dips365** [pnp/script-samples#44]
This script will be useful for reset permission to parent inheritance from Unique permission.
Scenario:
In document library, more than 400 folders and each folder has number of files. Now, Some file has unique permission which needs to be inherited from parent folder. In this case, Script will be worked to reset permission in all files which have unique permission in all folders.

**Comment by dips365** [comment]
could you please assign to me ?

**Comment by pkbullock** [comment]
Its alive now - thank you I will socialise soon :-)
