### ISSUE TITLE
💡Sample Idea: Adding set of test users

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#458]
Write a PowerShell script for creating a set of user accounts using the Microsoft Graph/PnP PowerShell or CLI. 

Optionally, there is potentially asking Chat GPT to create the list of users and names (there is a Chat GPT example recently added)

Example I saw recently was on Twitter where a member of the community wanted 400 user accounts to test an app.

**Comment by ValerasNarbutas** [comment]
@pkbullock  very interesting example, i want to do it :) please assign me

**Comment by ValerasNarbutas** [comment]
> Write a PowerShell script for creating a set of user accounts using the Microsoft Graph/PnP PowerShell or CLI.
> 
> Optionally, there is potentially asking Chat GPT to create the list of users and names (there is a Chat GPT example recently added)
> 
> Example I saw recently was on Twitter where a member of the community wanted 400 user accounts to test an app.

"there is a Chat GPT example recently added" - you mean the one in SPFx samples?

**Comment by pkbullock** [comment]
This sample: https://pnp.github.io/script-samples/graph-openai-get-page-summary/README.html

It was only an idea might not work - AI is a hot topic atm so would be about her cool use.

**Comment by ValerasNarbutas** [comment]
> This sample: https://pnp.github.io/script-samples/graph-openai-get-page-summary/README.html
> 
> It was only an idea might not work - AI is a hot topic atm so would be about her cool use.

ahh, latest one.. intresting interesting 🤔, i will try

**Comment by ValerasNarbutas** [comment]
@pkbullock this one done, was really fun to try this :) 
had to juggle a bit with a response frpm chat gpt but made it.

**Comment by pkbullock** [comment]
CLosing as complete :-D
