### ISSUE TITLE
Invoke-PnPSiteTemplate including list items and documents

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#461]
A sample showing how the to use the provisioning engine to ensure your newly created site contain a number of liste item and documents once the end user gets access

**Comment by kasperbolarsen** [comment]
Hi @pkbullock , will spo-apply-pnptemplate-with-files-and-listitems do as a name for this one?

**Comment by pkbullock** [comment]
Looks good @kasperbolarsen 😊

**Comment by pkbullock** [comment]
You can drop it makes sense. I suspect most won't pay too much attention to url.
