### ISSUE TITLE
spo-generate-sp-storage-savings-report Interactive logining

### ISSUE THREAD

**Issue by wptheme4me** [pnp/script-samples#475]
We are using MFA for our users in tenant.
Can't run script successfully as it prompts:  Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

How to alter script for such scenario?

**Comment by kasperbolarsen** [comment]
Please see https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html  , I think using either -useWebLogin or -interactive should do the trick

**Comment by wptheme4me** [comment]
Thanks for suggestions.

> Please see https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html , I think using either -useWebLogin or -interactive should do the trick

Not sure how is to use -useWebLogin parameter in the script for better efficiency, as having >100 sites it will get cumbersome as it will show login window each time for each site in the loop. Is it possible to login once and loop over all sites?

**Comment by kasperbolarsen** [comment]
As I recall it -useWebLogin should cache the connection and NOT cause a login for each site collection

**Comment by pkbullock** [comment]
Closing as old issue/no response, feel free to reopen, if not the case.
