### ISSUE TITLE
spo-request-pnp-reindex-user-profile  - json error

### ISSUE THREAD

**Issue by till-llit** [pnp/script-samples#476]
this script will fail if department contains backslash characters - the json is not properly escaped and will result in a failed job.

example error message: 
DataFileNotJson		Bad JSON escape sequence: \V. Path 'value[1672].Department', line 1, position 150235.'

example json

`       {
            "IdName": "id",
            "Department": "COM\DEPARTMENT1"
        },`

**Comment by ValerasNarbutas** [comment]
@till-llit sample updated should be working fine now with symbols like "\". Incode I added a part to check breaking characters first and escape it.

**Comment by pkbullock** [comment]
Closing as complete
