### ISSUE TITLE
Find all items with unique permissions and export to csv

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#478]
Items where the permissions have been broken can be a pain in the neck and should according to statements from MS also cause a performance hit.
This script ( in PnP PowerShell ) will provide the decision makers with an actionable overview.

**Comment by pkbullock** [comment]
Nice item level. Saw this one for lists itself https://pnp.github.io/script-samples/spo-get-lists-libraries-item-count-permissions/README.html

**Comment by pkbullock** [comment]
Closing as sample is now complete :-)
