### ISSUE TITLE
Find all classic pages with a friendly URL and export to csv

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#479]
On older tenants with a lot of classic publishing sites we still encounter pages with friendly URLs. Besides been hidden from SharePoint search these pages often causes headaches when updating sites. This scrip (in PnP.PowerShell)  will identify each page and provide an overview for the admins.

**Comment by pkbullock** [comment]
There is the modernisation scanner detects for those. https://learn.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner

Bert Jansen wrote this, should find the pages too.

**Comment by kasperbolarsen** [comment]
Hi @pkbullock It would make loads of sense if the scanner would detect those pages 🙂 They have alway been a pain.
Would the sample be of use? I use it from time to time in order to inventory a customer's tenant.

**Comment by pkbullock** [comment]
I haven't used the scanner myself, unsure if this does it.  This sample would give folks options. So I believe so.
