### ISSUE TITLE
Getting checked-out files in the tenant using Search

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#481]
It requires a lot of work to iterate all Site Collections looking for checked out files. If you can accept that the quality is slightly lower ( some sites or libraries might be excluded from Search) this script can provide the list of checkout file is minutes, not hours.

@pkbullock suggested title: spo-export-checked-out-files-in-tenant-using-search, OK ?

**Comment by pkbullock** [comment]
Looks good 😊

**Comment by kasperbolarsen** [comment]
done :-)
