### ISSUE TITLE
Submit graph API scripts

### ISSUE THREAD

**Issue by oliveir3** [pnp/script-samples#500]
Hi folks, 
I would like to submit 2 types of scripts 
1) Graph API scripts that use URI strings with Invoke-RestMethod to get data. 
2) EXO module PowerShell scripts. 
Can I contribute to the script-sample library? 
Thanks

**Comment by pkbullock** [comment]
Hi @oliveir3 yes, we support those script types. You might be the first EXO one but that's ok I can make adjustments. 

Thank you 🙏

**Comment by pkbullock** [comment]
Closing as low activity, however if you would like to contribute please let me know.
