### ISSUE TITLE
Add version comments to sample

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#521]
If this is supported, add version comments in sample

Reference PR #488

**Comment by fdj3580** [comment]
I hope someone is able to do this - I'm yet to find any example where it has been achieved.  It's easy enough to get the comment for the current version but seems very difficult to get the matching comment for each version.

**Comment by kasperbolarsen** [comment]
I'll have a go at this one, at least for PnP.PpowerShell :-)

**Comment by pkbullock** [comment]
Location of sample: https://github.com/pnp/script-samples/tree/main/scripts/spo-get-list-item-version-history

**Comment by kasperbolarsen** [comment]
Done

**Comment by pkbullock** [comment]
Closing as done :-)
