### ISSUE TITLE
Download an array of file urls and zip them

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#527]
Just an idea, and I will make the script if nobody else grabs it 😊

**Comment by ValerasNarbutas** [comment]
@pkbullock i can grab it, i need something similar.

**Comment by pkbullock** [comment]
Go for it, I have set assigned to.

**Comment by ValerasNarbutas** [comment]
Pull request ready #651

**Comment by pkbullock** [comment]
Closing as complete
