### ISSUE TITLE
Check each user profile against AD/AAD to determine which are active,  output to csv

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#543]
An idea

**Comment by pkbullock** [comment]
Nice idea, what actions are you defining as "activity". I know the sign-in logs/Graph equiv is heavily throttled.

**Comment by kasperbolarsen** [comment]
Not really sure which criteria to use, perhaps leave that choice for the people using the script. 
An option could be just to verify that the user exists in the AAD and isn't blocked.
Another could be to verify that the users activity using the audit log.
Any other ideas?
