### ISSUE TITLE
Idea: Bulk applying techniques

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#552]
This is a brain dump but thinking of standard techniques to apply configuration or lists, reporting, in bulk but generalized.  

e.g. 

 - JSON list of sites, configuration
 - CSV, Text Files
 
We have may samples covering different patterns, so just thinking of having a sample to cover some of those.

**Comment by kasperbolarsen** [comment]
Perhaps combining it with the SP Starter kit?
