### ISSUE TITLE
PNP powershell version for https://pnp.github.io/script-samples/spo-copy-list/README.html?tabs=cli-m365-ps

### ISSUE THREAD

**Issue by ValerasNarbutas** [pnp/script-samples#560]
Add pnp powershell version of this sript:
https://pnp.github.io/script-samples/spo-copy-list/README.html?tabs=cli-m365-ps

I will do it.

**Comment by pkbullock** [comment]
Thank you :-)

**Comment by ValerasNarbutas** [comment]
Sample updated @pkbullock
