### ISSUE TITLE
Sample - Replace Power Automate owner

### ISSUE THREAD

**Issue by nicodecleyre** [pnp/script-samples#566]
You know the feeling when someone leaves the company but he's single owner of a lot of flows? Let's write a sample script for that!

I would like to propose to write a script that replaces the owner on every flow he's owner of with another one. Replacement should happen based on the upn.

Script can be written with the CLI for Microsoft 365.

**Comment by pkbullock** [comment]
This is a great idea! Are you working on this or proposing it?

**Comment by nicodecleyre** [comment]
> This is a great idea! Are you working on this or proposing it?

I would like to work on this
