### ISSUE TITLE
Issues with SPO Generate SP Storage Saving Report PnP sample

### ISSUE THREAD

**Issue by chasquad** [pnp/script-samples#574]
I'm looking for some help with running the SPO Generate SP Storage Saving Report PnP sample.
https://pnp.github.io/script-samples/spo-generate-sp-storage-savings-report/README.html?tabs=pnpps

The script runs, takes a long time as there are 444 SP sites to go through.  It never writes an output file.  There is an error every so often in the screen output:

https://tenant.sharepoint.com/sites/Audit, number 80 of 444
Documents loading items
Documents , 706
added data for  Documents , EAS COA Update Log.xlsx
added data for  Documents , Oracle COA Update Log.xlsx
added data for  Documents , Allocation Rules 1Q23 Co 601.xlsx
added data for  Documents , Expense Allocation Q1_23 601 to 234 CEJ.xlsx
added data for  Documents , EAS Function Groups.xlsx
added data for  Documents , AP Period Close Reconciliation Schedule Jul23.xlsx
added data for  Documents , Company_Groups_ALS_Promotion.xlsx
added data for  Documents , AP Period Close Reconciliation Schedule Aug23.xlsx
skipping Style Library
      Error: Cannot validate argument on parameter 'Encoding'. The argument "utf8BOM" does not belong to the set "Unicode,UTF7,UTF8,ASCII,UTF32,BigEndianUnicode,Default,OEM" s
pecified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

I'm not sure if this is the cause of the output file not being created.  I've not customized the script other than setting the variables:

#Set Variables
$SharePointAdminSiteURL = "https://tenant-admin.sharepoint.com/"
$outputPath = "C:\scripts\versiontrimmer\"

$reducedNumberOfVersions = 1
$UsingIntractive = $false
$UsingCertificate = $true
$clientID = "5555d5b5-5c5-5de5-5b55-5fa5555cbbbf"
$tenantId = "tenant.onmicrosoft.com"
$certificatePassword = "killerpnpscript"
$certificatePath = "C:\scripts\pnp.pfx"

Any help on this issue would be greatly appreciated. Thanks!

**Comment by kasperbolarsen** [comment]
Sure :-) Let's start with getting it to work on a single site collection first.
Comment out the line $SiteCollections = [Get-PnPTenantSite](https://pnp.github.io/powershell/cmdlets/Get-PnPTenantSite.html) -Connection $conn
and insert this
$SiteCollections = Get-PnPTenantSite -Connection $conn  | Where-Object {$_.Url -eq "TheUrlOfYourTestSite"}   #the actual filter

Just checking, do you have a folder at $outputPath = "C:\scripts\versiontrimmer" ? You should have.

Regarding the UTF8BOM error: Try to replace utf8BOM til just UTF8

Hopes this will solve the issue :-)

**Comment by chasquad** [comment]
Thanks!

Yeah, I had the folder already created.  Changing the UTF8BOM to just be UTF seemed to fix the issue.  I'm rerunning the script now on all 444 sites and from what I can see so far, it has created the csv file.  

Question:  It is creating the output file as "1.csv"  Can I hardcode what I want the file to be named plus include the date in the name of when the script was run?

Thanks so much for your help in figuring this out.

**Comment by chasquad** [comment]
Thanks for the solution.
