### ISSUE TITLE
💡 Export text content from SharePoint Online pages to html

### ISSUE THREAD

**Issue by jackpoz** [pnp/script-samples#602]
Export the content of a SPO page to html, focusing mostly on the text and sort of ignoring images/etc.
This is needed when analysing the actual text with tools that don't support SPO but support html.

**Comment by jackpoz** [comment]
I have the script ready, just have to go through the steps of https://pnp.github.io/script-samples/contributing/preparing-a-submission.html . Opening this issue as suggested on https://pnp.github.io/script-samples/contributing/how-can-i-contribute.html

**Comment by pkbullock** [comment]
Sounds cool! lol I wrote a process to do the opposite recently, which I should really create a sample for.  Let me know if you need any help.
