### ISSUE TITLE
Export/import library folder structure using a json file

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/script-samples#617]

**Comment by kasperbolarsen** [comment]
@pkbullock should I split this into two samples , one for export and one for import ?

**Comment by pkbullock** [comment]
Looks fine to submit as one, you can always have two blocks of PowerShell one for export and in pop e for import. Anyway makes it simple?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pkbullock** [comment]
Reference #619 

Thanks Kasper, closing this.
