### ISSUE TITLE
Power App Description Exported to a Report

### ISSUE THREAD

**Issue by IfEyeOnlyKnew** [pnp/script-samples#631]
Based on this example, 
https://pnp.github.io/script-samples/powerapps-get-app-users-list-csv/README.html?tabs=powerapps-ps, can you also have the App Description exported as well?

**Comment by ValerasNarbutas** [comment]
> Based on this example, https://pnp.github.io/script-samples/powerapps-get-app-users-list-csv/README.html?tabs=powerapps-ps, can you also have the App Description exported as well?

Hi @IfEyeOnlyKnew 
yes you can but needs a bit more code.
@pkbullock  can you assign this to me? i will update code to get description and some additional details for the app

**Comment by pkbullock** [comment]
Thank you @ValerasNarbutas

**Comment by ValerasNarbutas** [comment]
@pkbullock update is ready,  @IfEyeOnlyKnew  new sample will also extract description and a bit more additional properties for the app.

**Comment by IfEyeOnlyKnew** [comment]
Thank you for the support.
