### ISSUE TITLE
Sample Idea: Navigation Node example

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#635]
See this tweet for inspiration: https://x.com/lshelton_tech/status/1734983430826303792?s=46&t=VqKJd3zMAWR2wGB7gXPdnw

**Comment by ValerasNarbutas** [comment]
Love to try !
looks like some digging might needed
@pkbullock please assign to me

**Comment by pkbullock** [comment]
Super cool @ValerasNarbutas thank you. 

I noticed the Get-PnPNavigationNode cmdlet had a tree option. Or alternatively try  PnP provisioning with the Navigation Handler only might be able to do the capture, tweak and apply. I sometimes revert to that. 

I didn't see an option for Set-PnPNavigationNode so might be a gap. Or having a "moment".

**Comment by ValerasNarbutas** [comment]
indeed looks like Set-PnPNavigationNode  is missing from pnp powershell, i manage tu make it happen anyway but probably add idea to the pnp powershell repo.
