### ISSUE TITLE
Enhancements: Remove language localization and unnecessary query string parameters from links

### ISSUE THREAD

**Issue by ganesh-sanap** [pnp/script-samples#654]
There are few links to Microsoft documentation articles (and maybe others) with default language localizations in URLs, like:

- `en-us` in https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps
- `en-us` in https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps

 and some unnecessary query string parameters in URLs, like:

- `view=whiteboard-ps` in https://docs.microsoft.com/en-us/powershell/module/whiteboard/?view=whiteboard-ps
- `view=sharepoint-ps` in https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps

Can we remove those from the repository? @pkbullock Let me know your thoughts on this.

**Comment by pkbullock** [comment]
This is a great idea! lets do this, is this one you want to do, if not happy to take this on?

**Comment by ganesh-sanap** [comment]
Please assign to me, will work on it today.
