### ISSUE TITLE
Modernize Blog Pages

### ISSUE THREAD

**Issue by nicole-ge** [pnp/script-samples#683]
Hi 
I want to Modernize classic blog page from SP2019 onprem to SPO using this script https://pnp.github.io/script-samples/modernize-blog-pages/README.html?tabs=pnpps

But it doesn't work. Can someone help please?

Kind regards

**Comment by pkbullock** [comment]
This post isnt optimised for On-Prem to Cloud modernisation, however, with some small tweaks to the Connect-PnPOnline with the OnPrem flag, you can establish the connection. 

https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#example-11

I've not tested recently, been a while, more tweaks to the script might be needed. Hope this helps.

**Comment by pkbullock** [comment]
Closing as answered.
