### ISSUE TITLE
Sample for bulk library generation - non provisioning engine

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#7]
Build a set of document libraries from PowerShell script but not using the provisioning engine

**Comment by dips365** [comment]
I would like to work on it. Could you please assign to me?
Not using Provisioning engine, Does that mean need to use Power shell commands only like New-PnPList ?

**Comment by pkbullock** [comment]
Yes, so building a library with a couple of columns + view maybe. Up to you how far, this is a demostration. Thank you for looking at this one 😊

**Comment by ValerasNarbutas** [comment]
@dips365 maybe you could also add an example of site design for list creation.

**Comment by pkbullock** [comment]
Hi @dips365 are you working on this or can i free up for other possible contributors?

**Comment by dips365** [comment]
Working on it !! Will complete it by very soon

**Comment by pkbullock** [comment]
Hi @dips365 are you working on this, if not i can release to the community or submit sample myself.

**Comment by Jwaegebaert** [comment]
Hey @pkbullock, can I take a shot at this new sample?

**Comment by pkbullock** [comment]
Sure, please do :-)
