### ISSUE TITLE
Create script for creating an equivelant to the PnP Management Shell app

### ISSUE THREAD

**Issue by pkbullock** [pnp/script-samples#728]
Based on the recent announcement, create a new Entra ID app that contains the same permissions and delegate as the existing PnP Management Shell. So this is CREATION of the app.

Consider creating for 

- PnP PowerShell (priority)
- CLI for Microsoft 365 (priority) 
- Azure ADK
- Azure CLI

I'm going to start this sample.  Please ping me if you are planning an equivalent sample.

**Comment by ValerasNarbutas** [comment]
submited pull request and  thought i need to create issue but looks like you did exactly the same just with a bit more info :)
https://github.com/pnp/script-samples/pull/738

**Comment by pkbullock** [comment]
Thank you @ValerasNarbutas 👏 - closing this one as complete.
